### ISSUE TITLE
Do we still need the `bottle` block?

### ISSUE THREAD

**Issue by zulhfreelancer** [k0sproject/homebrew-tap#13]
I'm referring to this section: https://github.com/k0sproject/homebrew-tap/blob/38bfbb99f673ca8870b59ee1a01302d371d25ef1/Formula/k0sctl.rb#L10-L14

From what I understand and see during `brew install k0sproject/tap/k0sctl`, it clones https://github.com/k0sproject/k0sctl repo and run the steps in its [Makefile](https://github.com/k0sproject/k0sctl/blob/main/Makefile). That happens for any OS/arch I believe.

I created a repo [here](https://gitlab.com/zulhfreelancer/find-k0sctl-release-hash/-/tree/master/) that contains all the checksums from k0sctl repo above (see download script [here](https://gitlab.com/zulhfreelancer/find-k0sctl-release-hash/-/blob/master/0-download.sh)) and when I [searched](https://gitlab.com/zulhfreelancer/find-k0sctl-release-hash/-/blob/master/1-find.sh) the two strings in the `bottle do` block above, I can't see any result. Meaning, there's no release matching those defined checksums.

Unless my understanding and methodology was wrong, I think we should remove that block to reduce confusion among users. Or to be better, I'd suggest replacing the current 'clone and build' steps to just 'download the right release for user's OS and arch'. [GoReleaser](https://goreleaser.com/customization/homebrew/) project can help with that.

**Comment by kke** [comment]
All the release automation, including the bottling, comes directly from homebrew's [`brew tap-new`](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) wizard. The `bottle` block is populated by the automation.

> hen I [searched](https://gitlab.com/zulhfreelancer/find-k0sctl-release-hash/-/blob/master/1-find.sh) the two strings in the bottle do block above, I can't see any result. Meaning, there's no release matching those defined checksums.

Those are checksums/id's for the precompiled binaries so that brew doesn't need to clone+build, it can just download the [bottled](https://docs.brew.sh/Bottles) binary. The clone+build definition is used by the github workflow to build the binaries and it's also useful for `brew install --HEAD`, which will clone+build the main branch without it having been released yet.

A binary-only formula will not pass brew's `brew audit` checks or [Acceptable formulae](https://docs.brew.sh/Acceptable-Formulae) and having the apps on homebrew-core is something that is desired in the future instead of maintaining a [vendor tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#official-vendor-taps) forever.

**Comment by zulhfreelancer** [comment]
Thank you for the explanation
